POST http://localhost:3001/signup
Content-Type: application/json

{
  "username": "jimmy",
  "email": "jimmy6@hotmail.com",
  "password": "Doors343727",
  "role": 1
}

###
POST http://localhost:3001/signin
Content-Type: application/json

{
  "email": "dlaw96@hotmail.com",
  "password": "Doors343727"
}

###
POST http://localhost:3001/blog/create
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxY2M5MWVlZTM1MGVkNjgxMGIwYjgzZiJ9LCJpYXQiOjE2NDA4NzIyNzl9.kh6IcIrsvyAA3L85z0ehVBsHCWq0_BW3KL0azh1p4ps

{
  "title": "yet another! post with authorization with specification",
  "body": "WOOT!"
}

###
PUT http://localhost:3001/blog/posts/61cf19186374e3e776790f22
Content-Type: application/json

{
  "title": "CHange is good",
  "body": "WOOT!"
}
###

PUT http://localhost:3001/blog/comment
Content-Type: application/json

{
  "comment": "CHange is good",
}


###
GET http://localhost:3001/blog/posts/61ccc13b2ee3ae026f14daaf

###
GET http://localhost:3001/admin/61cc91eee350ed6810b0b83f

###
GET http://localhost:3001/blog/posts